export const ErrorCodes = {
  E_BAD_REQUEST: "E_BAD_REQUEST",
  E_VALIDATION: "E_VALIDATION",
  E_NOT_FOUND: "E_NOT_FOUND",
  E_UNAUTHORIZED: "E_UNAUTHORIZED",
  E_RATE_LIMIT: "E_RATE_LIMIT",
  E_IDEMPOTENCY_CONFLICT: "E_IDEMPOTENCY_CONFLICT",
  E_JOB_NOT_FOUND: "E_JOB_NOT_FOUND",
  E_JOB_CANCELLED: "E_JOB_CANCELLED",

  E_INTERNAL: "E_INTERNAL",
  E_NOT_IMPLEMENTED: "E_NOT_IMPLEMENTED",
  E_STEEL_TIMEOUT: "E_STEEL_TIMEOUT",
  E_STEEL_UNAVAILABLE: "E_STEEL_UNAVAILABLE",
  E_LLM_QUOTA: "E_LLM_QUOTA",
  E_LLM_TIMEOUT: "E_LLM_TIMEOUT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
